### ISSUE TITLE
Setup MLFlow Experiment Tracking Code

### ISSUE THREAD

**Issue by paulomaia20** [dmangonakis/Social_Bias_Detection#5]
Setup MLFlow Experiment Tracking Code. 

How do we setup MLFlow?

How do we train a model and save its parameters? Can do this with a mock model from Pytorch if needed

Include a README explaining how to install everything

**Comment by Jimaras08** [comment]
Added mock model with Python 3.9.1 - 64 Bit: https://github.com/dmangonakis/Yelp_Dataset/tree/pytorch_mlflow_101

Experiment Tracking Code via `mlflow.pytorch`: Just `mlflow.pytorch.autolog` before "fit". You should get the following output:

![2021-01-15 10_32_27-Window](https://user-images.githubusercontent.com/54860863/104707675-01c09b00-571d-11eb-9d7f-5470c1485467.jpg)

Then start the UI with `mlflow ui` and go to `http://localhost:5000/#/`:

![2021-01-15 10_34_27-Window](https://user-images.githubusercontent.com/54860863/104707870-451b0980-571d-11eb-91f0-5c72cf4a716f.jpg)

**Comment by Jimaras08** [comment]
We should now consider having a backend store and a artifact store.

- backend store: experiments, metadata, params, metrics, tags, runs
- artifact store: models

Backend Store can either be file store or database-backed store (`['postgresql', 'mysql', 'sqlite', 'mssql']`). Decision?

Artifact Store can either be file store of storage store (S3, Azure Blob Storage, Google Cloud Storage, SFTP, NFS). Decision?
