### ISSUE TITLE
Create a dashboard for predicting the score of a review

### ISSUE THREAD

**Issue by paulomaia20** [dmangonakis/Social_Bias_Detection#9]
Create a dashboard for predicting the score of a review, given the text

Can also do a "game" where you try to guess the review score and it gives you the real score

**Comment by Jimaras08** [comment]
![2021-01-25 13_12_53-Streamlit](https://user-images.githubusercontent.com/54860863/105704644-67780880-5f0f-11eb-9676-5b84523de99b.jpg)

https://share.streamlit.io/dmangonakis/yelp_dataset/streamlit/src/app/main.py
